plugins {
    id 'com.android.application'
}

android {
    namespace 'com.baidumap.demo'
    compileSdk 34

    defaultConfig {
        applicationId "com.baidumap.demo"
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName "1.2"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
